### ISSUE TITLE
edit wizards

### ISSUE THREAD

**Issue by EKluitenberg** [elfuego/tacticalmediafiles#2]
Media editor is vervallen - dat linkte naar een systeem dat niet meer werkt en specifiek voor de darwin streaming server was gebouwd - kan dus vervallen.

Update tagcloud: zou handig zijn als dat automatisch gebeurt als je ergens een tag (keyword) toevoegt.

Connect Media Objects zou eigenlijk een link naar generieke editor voor video moeten worden (waar je dus ook relaties met artikelen e.d. kunt aangeven). Misschien moet dat in 1 keer op een logische manier samen gaan met de nieuwe video functionaliteit. Dat kun jij beter beoordelen.

Copyright moet blijven - hebben we weinig gebruikt maar wordt belangrijker in de toekomst om ook andere licenties aan te kunnen maken. 

Types zou eigenlijk beter in de betreffende velden in de wizards zelf kunnen zitten, maar hoeft niet apart in deze lijst.

Organisation kan weg (mag ook blijven als het al is gedaan), maar in de volgende fase moet een mogelijkheid worden gecreëerd om ipv een persoon ook een organisatie als auteur / initiator van iets aan te geven, met een pagina zoals een persoon - kan misschien ook door type te gebruiken, maar dan moet het aan de voorkant ook zichtbaar worden dat het geen persoon maar een organisatie is - punt voor later, nu niet essentieel.

**Comment by elfuego** [comment]
All done I believe.
